import * as WeaponProps from './WeaponProperties.mjs';


const {
  AccFireInterpSpeed,
  AccFirePenalty,
  AimError,
  bOverrideAnimsets,
  bRemapAccToRecoil,
  bScaleFireAnimByFireRate,
  Components,
  DamageRange,
  Description,
  DrawAnimset,
  FemaleWeaponAnimSets,
  FireMode,
  FiringShake,
  getFireMode,
  getFiringShake,
  getString,
  HeadshotDamageMultiplier,
  HeatLossRateRange,
  HeatPerShotRange,
  idWithBling,
  m_bIsMuzzleFlashVFXEnabled,
  m_bShootingWhileOverheatedSoundPlayed,
  m_fOverlapRecurseBreakoutDistance,
  m_fProjectilesSpreadModifier,
  m_fSniperFireDistance,
  m_fVehicleFireDistance,
  m_fWeaponFireDistance,
  m_ImpactParameterName,
  m_MuzzleCamSocketName,
  m_MuzzleSocketName,
  m_nCloseStripLength,
  m_nTotalNumberCloseStrips,
  m_nTotalNumberStrips,
  m_pDamage,
  m_SourceParameterName,
  MaleWeaponAnimSets,
  Mesh,
  MinPelletsForPhysics,
  PelletSpread,
  PortArmsAssaultDistance,
  PortArmsPistolDistance,
  PortArmsShotgunDistance,
  PortArmsSniperDistance,
  RampFirePct,
  RampFireTime,
  RateOfFire,
  Recoil,
  RecoilFadeSpeed,
  RecoilYawFrequency,
  RecoilYawScale,
  RecoilZoomFadeSpeed,
  SkelMeshComp,
  TightAimFiringShake,
  UIDPSFudgeFactor,
  WeaponFireRumble,
  WeaponOverheatedRumble,
  ZoomAccFireInterpSpeed,
  ZoomAccFirePenalty,
  ZoomAimError,
  ZoomRecoil
} = WeaponProps;


class Weapon {
  constructor(config) {
    MaleWeaponAnimSets
    PelletSpread
    AccFireInterpSpeed
    AccFirePenalty
    AimError
    bOverrideAnimsets
    bRemapAccToRecoil
    bScaleFireAnimByFireRate
    Components
    DamageRange
    Description
    DrawAnimset
    FemaleWeaponAnimSets
    FireMode
    FiringShake
    HeadshotDamageMultiplier
    HeatLossRateRange
    HeatPerShotRange
    m_bIsMuzzleFlashVFXEnabled
    m_bShootingWhileOverheatedSoundPlayed
    m_fOverlapRecurseBreakoutDistance
    m_fProjectilesSpreadModifier
    m_fSniperFireDistance
    m_fVehicleFireDistance
    m_fWeaponFireDistance
    m_ImpactParameterName
    m_MuzzleCamSocketName
    m_MuzzleSocketName
    m_nCloseStripLength
    m_nTotalNumberCloseStrips
    m_nTotalNumberStrips
    m_pDamage
    m_SourceParameterName
    Mesh
    MinPelletsForPhysics
    PortArmsAssaultDistance
    PortArmsPistolDistance
    PortArmsShotgunDistance
    PortArmsSniperDistance
    RampFirePct
    RampFireTime
    RateOfFire
    Recoil
    RecoilFadeSpeed
    RecoilYawFrequency
    RecoilYawScale
    RecoilZoomFadeSpeed
    SkelMeshComp
    TightAimFiringShake
    UIDPSFudgeFactor
    WeaponFireRumble
    WeaponOverheatedRumble
    ZoomAccFireInterpSpeed
    ZoomAccFirePenalty
    ZoomAimError
    ZoomRecoil
  }
}